#!/bin/bash

if [[ EUID -ne 0 ]]; then 
	echo "This script must be run as root"
	exit 1
fi

#Variables
newusername=""
newuserpass=""

#Wrong Args
wrongargs() {
	echo "Wrong arguments"
	echo "Try: addprogrammer -u <USERNAME> -p <PASSWORD>"
	exit 1
}

#Parse args
while [ "$1" != "" ]; do
	if [ "$1" = "-u" ]; then
		shift
		newusername="$1"
		if [ -z newusername ]; then
			wrongargs
		fi
	elif [ "$1" = "-p" ]; then
		shift
		newuserpass="$1"
		if [ -z newuserpass ]; then
			wrongargs
		fi
	else
		wrongargs
	fi
	shift
done

#Add user
useradd $newusername
echo "$newusername:$newuserpass" | chpasswd
usermod -a -G biurocracy $newusername
#Make directories and make them low on memory or something

