#!/bin/bash

if [[ $EUID -ne 0 ]]; then 
	echo "This script must be run as root"
	exit 1
fi

#Group management
groupadd biurocracy

#Add user
useradd biuro
echo "biuro:111" | chpasswd

usermod -a -G biurocracy biuro

#Make directories and make them low on memory or something

mkdir /home/biuro
chown biuro:biurocracy /home/biuro
chmod 555 /home/biuro
