#!/bin/bash

#File can only be executed by root
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root"
	exit 1
fi

#Variables
newusername=""
newuserpass=""
issuperbiuro=0

#If args are wrong
wrongargs() {
	echo "Wrong arguments"
	echo "Try: addbiuro -u <USERNAME> -p <PASSWORD>"
	exit 1
}

#If there are no args
if [ -z "$1" ]; then
	wrongargs
fi

#If there is at least one arg
while [ "$1" != "" ]; do
	if [ "$1" = "-u" ]; then
		shift
		newusername="$1"
		if [ -z newusername ]; then
			wrongargs
		fi
	elif [ "$1" = "-p" ]; then
		shift
		newuserpass="$1"
		if [ -z newuserpass ]; then
			wrongargs
		fi
	elif [ "$1" = "-k" ]; then
		issuperbiuro=1
	else
		wrongargs
	fi
	shift
done

#Add user and set password
useradd $newusername
echo "$newusername:$newuserpass" | chpasswd

#Make directories
mkdir /home/$newusername
mkdir /home/$newusername/Downloads
mkdir /home/$newusername/Desktop
mkdir /home/$newusername/Documents
mkdir /home/$newusername/Music
mkdir /home/$newusername/Pictures
mkdir /home/$newusername/Public
mkdir /home/$newusername/Templates
mkdir /home/$newusername/Videos
mkdir /home/$newusername/.ssh

#Set ownership
chown -R "$newusername":"$newusername" /home/$newusername
chmod -R 700 /home/$newusername

#Set server "domain"
echo "10.0.2.10    server" >> /etc/hosts

#Generate rsa key and send it to server
runuser -l "$newusername" -c "ssh-keygen -t rsa -N $newuserpass -f /home/$newusername/.ssh/id_rsa"
chmod 755 /home/$newusername/.ssh/id_rsa.pub
apt-get install -y sshpass
runuser -l "biuro" -c "sshpass -p 111 ssh-copy-id biuro@server"

# Is he normal biuro worker or super biuro worker ?
groupadd superbiuro
groupadd biurocracy

if [ "issuperbiuro" = "1" ]; then
	usermod -a -G superbiuro $newusername
else
	usermod -a -G biurocracy $newusername
fi

#Nfs Config
apt-get install -y nfs-common
sed -i '/^\[General\]$/a Domain = servernfs' /etc/idmapd.conf
mkdir -p /nfs/import
ln -s /nfs/import/ /home/$newusername/Raports
chown -R root:superbiuro /nfs/import
chmod -R 775 /nfs/import 
mount -t nfs server:/nfs/raports /nfs/import

#Restrict shell
chsh -s /bin/rbash $newusername

#Install skype
wget https://go.skype.com/skypeforlinux-64.deb
apt install ./skypeforlinux-64.deb
rm ./skypeforlinux-64.deb
