#!/bin/bash

if [[ $EUID -ne 0 ]]; then 
	echo "This script must be run as root"
	exit 1
fi

#Group management
groupadd programmers

#Add user
useradd programmer
echo "programmer:111" | chpasswd

usermod -a -G programmers programmer

#Make directories and make them low on memory or something

mkdir /home/programmer
chown programmer:programmers /home/programmer
chmod 555 /home/programmer
